### ISSUE TITLE
Establecer conexión de la App con la DB

### ISSUE THREAD

**Issue by maiamajzum** [maiamajzum/InstaTURNO--Grupo4--DS-IA#13]
- Se requiere instanciar el archivo de conexión a la base de datos (`conectar_base_datos.py`) que acompañará los diferentes `releases`.
- Validar la exposición de `credenciales` de conexión.

**Comment by 30matias30** [comment]
La primer versión de conexión a la DB está subida --> Carpeta-Temporal --> 0.1v

Revisar las credenciales para ingresar
