### ISSUE TITLE
Error en la impresión de ID de TURNO en la Creación de Turno

### ISSUE THREAD

**Issue by maiamajzum** [maiamajzum/InstaTURNO--Grupo4--DS-IA#17]
https://github.com/maiamajzum/InstaTURNO--Grupo4--DS-IA/blob/10c0ee19282b7ffdf566580ebe13df9885db8f5c/Carpeta-Temporal/0.4v/crear_turno.py#L52

**Comment by marcosgfrites** [comment]
La [corrección del error](https://github.com/maiamajzum/InstaTURNO--Grupo4--DS-IA/blob/3a88596ac4b781075ffdb012af8fb630a99cc0b0/Carpeta-Temporal/0.5v/crear_turno.py#L52), finalmente la pudimos visualizar en la meeting grupal de `Pair Programming`.

Estábamos retornando por pantalla la variable completa `c` que era una lista, mientras sólo necesitábamos centrarnos en la posición '0' de dicho objeto.

Queda corregido el error. Se imprime sólo el ID.
