### ISSUE TITLE
Testing y Code Review

### ISSUE THREAD

**Issue by maiamajzum** [maiamajzum/InstaTURNO--Grupo4--DS-IA#18]
- Se requiere revisar el funcionamiento de la aplicación conjuntamente con la base de datos.
- Validar el correcto enlace entre archivos de Python.

**Comment by marcosgfrites** [comment]
- Se realiza una revisión completa del código y fue necesario implementar un refactor sobre la ruta de conexión al archivo `conectar_base_datos.py`.
- Posterior a ello fue necesario realizar refactor de las rutas de las sentencias `import` que hacían llamado a los archivos `conectar_base_datos.py`, `APLICACION.mysql` y `APLICACION.tabulate`.
