### ISSUE TITLE
Revisión general del funcionamiento de la App

### ISSUE THREAD

**Issue by maiamajzum** [maiamajzum/InstaTURNO--Grupo4--DS-IA#19]
- Se requiere realizar pruebas funcionales de punta a punta de cada una de las funcionalidades existentes en la app.

**Comment by marianaalcalde** [comment]
La mayoría de los usuarios reportan adecuado funcionamiento de las aplicación. Se observa una falla aislada en un usuario que amerita mayor exploración. Se continúa el análisis por separado.
