### ISSUE TITLE
Análisis de reporte de error en usuario aislado para la creación de BD de la app. 

### ISSUE THREAD

**Issue by maiamajzum** [maiamajzum/InstaTURNO--Grupo4--DS-IA#20]

**Comment by marianaalcalde** [comment]
Si bien la mayoría de los usuarios informan que han podido correr los scripts de creación y población de base de datos, se evidencia un reporte de interrupción del proceso a nivel local del usuario que indica: "error 6125: failed to add the foreign key constraint. missing unique key for constraint 'fk_medico_has_horario_medico1' in the referenced table 'medico'". Una exploración inicial hipotetiza una dificultad en la versión de MySQL. Se verificará la solución para informar en la documentación de la aplicación para futuros usuarios.

**Comment by marianaalcalde** [comment]
Reiterado reportes en la comunidad informática previenen de la existencia de una reciente incorporación en la versión My SQL8.4 de una variable que restringe la posibilidad de creación de claves foráneas vinculadas a claves no únicas, lo que puede suceder en el caso del empleo de claves primarias compuestas, tal como ha sucedido en el error detectado en nuestra aplicación. Esta variable, disponible a partir de la versión de MySQL8.4 se encuentra inhabilitada por default y debe activarse para permitir que el programa corra. Aún así, el sistema informará una advertencia, dado que considera de escasa seguridad este tipo de diseño. Más información sobre la variable incorporada: [https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_restrict_fk_on...](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_restrict_fk_on_non_standard_key)
